apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 407291110458.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googleclothes:9a308c4221248a658dfc4a99e5d4ff27910759df
        ports:
        - containerPort: 80
