apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 407291110458.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-electronics:11abb160674c6ded182f361b6b233e484f0462d7
        ports:
        - containerPort: 80
