apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 407291110458.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlemusic:11abb160674c6ded182f361b6b233e484f0462d7
        ports:
        - containerPort: 80
