apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 407291110458.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlemusic:016a4ec8e2c94e2d174f1b847fd192abc4ade723
        ports:
        - containerPort: 80
