apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 407291110458.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlemusic:b0ac803b1586dcc7a20c9c548d7b012a716d9937
        ports:
        - containerPort: 80
