apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 407291110458.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-computers:2f0e5bde82447a1eb9b956b1019d7193d768e250
        ports:
        - containerPort: 80
