apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-computers:942b68e830a7e8f6be7486570cd4813650dc6824
        ports:
        - containerPort: 80
