apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-phones:9c57a7dac85f9f09ebcc31cf14870f5788f9e776
        ports:
        - containerPort: 80
