apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 407291110458.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-phones:2f0e5bde82447a1eb9b956b1019d7193d768e250
        ports:
        - containerPort: 80
